title: Mapping Loss — Libraries and Lives in Palestine
logo: /assets/img/logo.png
description: Libraries are not just repositories of books—they are symbols of memory, culture, and resistance. In Palestine, the destruction of libraries is not an isolated act of war; it represents a broader erasure of heritage. This project visualizes the destruction of Palestinian libraries alongside the lives lost on or around the same dates, creating a powerful data-driven narrative that links cultural annihilation with human tragedy.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
